services:
  backup:
    image: phalouvas/erpnext-worker:${ERPNEXT_VERSION}
    entrypoint: ["bash", "-c"]
    command:
      - bench --site all backup
    networks:
      bench-network: null
      mariadb-network: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
