version: "3.7"
services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    ports:
    - mode: ingress
      target: 80
      published: 8082
      protocol: tcp
    environment:
      - PMA_HOSTS=mariadb
      - PMA_PORTS=3306
      - UPLOAD_LIMIT=2000M
    volumes:
    - type: volume
      source: phpmyadmin-data
      target: /sessions
      volume: {}

  mariadb:
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql

  redis-cache:
    image: redis:alpine
    volumes:
      - type: volume
        source: redis-cache-data
        target: /data
        volume: {}

  redis-queue:
    image: redis:alpine
    volumes:
      - type: volume
        source: redis-queue-data
        target: /data
        volume: {}

  redis-socketio:
    image: redis:alpine
    volumes:
      - type: volume
        source: redis-socketio-data
        target: /data
        volume: {}

  frappe:
    image: frappe/bench:latest
    command: sleep infinity
    environment:
      - SHELL=/bin/bash
    volumes:
      - ..:/workspace:cached
      # Enable if you require git cloning
      # - ${HOME}/.ssh:/home/frappe/.ssh
    working_dir: /workspace/development
    ports:
      - 8000-8005:8000-8005
      - 9000-9005:9000-9005
      - mode: ingress
        target: 8000
        published: "8580"
        protocol: tcp

volumes:
  mariadb-data:
  redis-cache-data:
  redis-queue-data:
  redis-socketio-data:
  phpmyadmin-data:
